fail_fast: true

repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.9.6
  hooks:
  - id: ruff-format
    files: ^src/
    exclude: ^tests/
    args: [ src ]
  - id: ruff
    files: ^src/
    exclude: ^tests/
    args: [ "--fix", "--exit-non-zero-on-fix" ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: [ "src" ]

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.393
  hooks:
  - id: pyright
    args: [ src ]
    language: system

- repo: https://github.com/terrencepreilly/darglint
  rev: v1.8.1
  hooks:
  - id: darglint

- repo: local
  hooks:
    - id: pytest
      name: pytest
      entry: poetry run pytest
      language: system
      pass_filenames: false
      always_run: true