local:
  LOG_LEVEL: "DEBUG"
  DB_TYPE: "mysql"
  DB_HOST: "localhost"
  DB_PORT: 33306
  DB_DATABASE: "personal_cpa"
  DB_USERNAME: "application_user"
  DB_PASSWORD: "123qwe"
  DB_ROOT_PASSWORD: "1234qwer"
  DB_POOL_CONNECTION_LIMIT: 10
  DB_POOL_MAX_IDLE: 9
  DB_POOL_IDLE_TIMEOUT: 60000
prod:
  LOG_LEVEL: "DEBUG"
  DB_TYPE: "mysql"
  DB_HOST: "prod-test"
  DB_PORT: 3306
  DB_DATABASE: "personal_cpa"
  DB_USERNAME: "application_user"
  DB_PASSWORD: "123qwe"
  DB_ROOT_PASSWORD: "1234qwer"
  DB_POOL_CONNECTION_LIMIT: 10
  DB_POOL_MAX_IDLE: 9
  DB_POOL_IDLE_TIMEOUT: 60000
