# https://taskfile.dev

version: "3"

tasks:
  # ----------------------------------------------------------------------------
  # Init setting
  # ----------------------------------------------------------------------------

  init-setting:
    summary: Package initial setting
    cmds:
      - pyenv virtualenv 3.13.1 personal_cpa
      - poetry install --no-root --with dev
      - pre-commit install

  # ----------------------------------------------------------------------------
  # Backend Server
  # ----------------------------------------------------------------------------

  run-server:
    summary: Run the server
    cmds:
    - uvicorn personal_cpa.main:app --host 0.0.0.0 --port 8000 --reload

  # ----------------------------------------------------------------------------
  # Code Quality
  # ----------------------------------------------------------------------------

  code-clean:
    summary: Clean the code (lint, isort, format)
    cmds:
    - ruff format .
    - ruff check . --fix
    - pyright .

  test:
    summary: Run the tests
    cmds:
    - pytest
