# https://taskfile.dev

version: "3"

tasks:

  # ----------------------------------------------------------------------------
  # Formatting
  # ----------------------------------------------------------------------------

  code-fix:
    summary: Fix the code (lint, isort, format)
    cmds:
    - ruff check . --fix
