# https://taskfile.dev

version: "3"

tasks:
  # ----------------------------------------------------------------------------
  # Backend Server
  # ----------------------------------------------------------------------------
  dev-local:
    summary: Run the server
    cmds:
      - uvicorn personal_cpa.main:app --host 0.0.0.0 --port 8000 --reload
